services:
  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres-gitea:5432
      GITEA__database__NAME: ${DB_NAME}
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: ${DB_PASSWORD}
    volumes:
      - gitea:/data # Alternatively: use './data/gitea:/data' for local project storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea-net
    ports:
      - "3000:3000" # Web UI
      - "222:22" # SSH access
    restart: always
    depends_on:
      - postgres-gitea

  postgres-gitea:
    image: postgres:17
    container_name: postgres-gitea
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data # Alternatively: use './data/postgres:/var/lib/postgresql/data'
    networks:
      - gitea-net
    restart: always

volumes:
  gitea:
  postgres-data:

networks:
  gitea-net:
    external: false