services:
  mariadb-zabbix:
    image: mariadb:10
    container_name: mariadb-zabbix
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # config do .env
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - db_data:/var/lib/mysql
    networks:
        - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    depends_on:
        - mariadb-zabbix
    environment:
      DB_SERVER_HOST: mariadb-zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
        - "10051:10051"  # Porta padrão do Zabbix Server
    volumes:
        - zabbix-server-data:/var/lib/zabbix
        - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
        - zabbix-export-data:/var/lib/zabbix/export
    restart: unless-stopped
    networks:
        - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - mariadb-zabbix
    environment:
      DB_SERVER_HOST: mariadb-zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}  # fuso do php
    ports:
        - "8080:8080"   # HTTP
        - "8443:8443"   # HTTPS
    restart: unless-stopped
    volumes:
        - zabbix-web-data:/usr/share/zabbix
    networks:
        - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_ACTIVE: zabbix-server
    restart: unless-stopped
    networks:
      - zabbix-net

volumes:
    db_data:
    zabbix-web-data:
    zabbix-server-data:
    zabbix-snmptraps-data:
    zabbix-export-data:

networks:
    zabbix-net:
        driver: bridge
